# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=191, null=True)),
                ('account_number', models.CharField(default='', max_length=191, null=True)),
                ('bank', models.CharField(default='', max_length=191, null=True)),
                ('bank_account_number', models.CharField(default='', max_length=191, null=True)),
                ('bank_holder_name', models.CharField(default='', max_length=191, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'tc_org',
                'verbose_name': 'TC Org',
                'verbose_name_plural': 'TC Orgs',
            },
        ),
    ]
