# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180502_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcgroup',
            name='bank',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tcgroup',
            name='bank_account_number',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tcgroup',
            name='bank_holder_name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tcgroup',
            name='org_name',
            field=models.CharField(max_length=191, null=True),
        ),
    ]
