# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tcorg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcorg',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='tcorg',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='tcorg',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='tcorg',
            name='bank_holder_name',
        ),
    ]
