# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180503_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcgroup',
            options={'managed': True, 'verbose_name': 'TC Group', 'verbose_name_plural': 'TC Groups'},
        ),
        migrations.AlterModelOptions(
            name='tcpickteam',
            options={'managed': True, 'verbose_name': 'TC Pickteam', 'verbose_name_plural': 'TC Pickteams'},
        ),
        migrations.AlterModelOptions(
            name='tcretailer',
            options={'managed': True, 'verbose_name': 'TC Retailer', 'verbose_name_plural': 'TC Retailers'},
        ),
        migrations.AlterModelOptions(
            name='tcuser',
            options={'managed': True, 'verbose_name': 'TC User', 'verbose_name_plural': 'TC Users'},
        ),
    ]
