# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-14 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180503_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('ws_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('ws_phone', models.CharField(max_length=12)),
                ('product_name', models.CharField(max_length=50)),
                ('sizencolor', models.CharField(db_column='sizeNcolor', max_length=1024)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, default='', max_length=30)),
                ('location', models.CharField(blank=True, default='', max_length=30)),
                ('memo', models.CharField(blank=True, default='', max_length=100)),
                ('updated_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
                ('is_deleted', models.CharField(blank=True, max_length=10, null=True)),
                ('notify_id', models.CharField(default='', max_length=100)),
                ('building', models.CharField(default='', max_length=100)),
                ('pickteam_id', models.IntegerField()),
                ('retailer_name', models.CharField(default='', max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='tcgroup',
            name='account_number',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tcgroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
