# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181001_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcretailer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tcretailer',
            name='biz_num',
        ),
        migrations.RemoveField(
            model_name='tcretailer',
            name='biz_type',
        ),
        migrations.RemoveField(
            model_name='tcretailer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tcretailer',
            name='store_type',
        ),
    ]
