# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180503_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcgroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
