# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181001_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcretailer',
            name='order_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OrderFormats'),
        ),
    ]
