# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-01 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181001_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcretailer',
            name='pickteam_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ret_pt', to='app.TCOrg'),
        ),
    ]
