# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-02 01:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('app', '0007_tcretailer_pickteam_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCOrg1',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('org_name', models.CharField(max_length=191, null=True)),
                ('account_number', models.CharField(default='', max_length=191, null=True)),
                ('bank', models.CharField(default='', max_length=191, null=True)),
                ('bank_account_number', models.CharField(default='', max_length=191, null=True)),
                ('bank_holder_name', models.CharField(default='', max_length=191, null=True)),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'tc_org1',
                'verbose_name_plural': 'TC Orgs',
                'verbose_name': 'TC Org',
            },
            bases=('auth.group',),
        ),
    ]
