# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180615_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='WsByRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_name', models.CharField(max_length=30)),
                ('building_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('floor', models.CharField(max_length=30)),
                ('ws_phone', models.CharField(max_length=30)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TCRetailer')),
            ],
            options={
                'verbose_name': "TCRetailer's Wholesaler",
                'verbose_name_plural': "TC Retailers's Wholesalers",
                'managed': True,
                'db_table': 'WsByRetailer',
            },
        ),
        migrations.AlterModelOptions(
            name='ws',
            options={'managed': True},
        ),
    ]
