# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-02 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181002_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcorg1',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='tcorg1',
            name='main_user',
        ),
        migrations.DeleteModel(
            name='TCOrg1',
        ),
    ]
