# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180625_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ws',
            options={'managed': False},
        ),
    ]
