# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-02 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('app', '0009_auto_20181002_1118'),
    ]

    operations = [
    ]
