# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-02 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181002_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcorg',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
    ]
