# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180625_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wsbyuser',
            old_name='building_name',
            new_name='building',
        ),
    ]
