# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180625_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsbyuser',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 0, 17, 13, 644744), null=True),
        ),
        migrations.AlterModelTable(
            name='wsbyuser',
            table='wsbyuser',
        ),
    ]
