# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181002_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsbytcgroup',
            name='org',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.TCOrg'),
        ),
    ]
