# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181003_1924'),
    ]

    operations = [
    ]
