# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180627_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsbyuser',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
