# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180627_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFormats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmt_name', models.CharField(default='', max_length=10, verbose_name='포맷명')),
                ('fmt_ws_name', models.CharField(max_length=10, verbose_name='도매명 포맷')),
                ('fmt_product_name', models.CharField(max_length=10, verbose_name='장끼명 포맷')),
                ('fmt_sizeNcolor', models.CharField(max_length=10, verbose_name='사이즈 및 컬러 포맷')),
                ('fmt_color', models.CharField(max_length=10, verbose_name='컬러 포맷')),
                ('fmt_price', models.CharField(max_length=10, verbose_name='도매가 포맷')),
                ('fmt_count', models.CharField(max_length=10, verbose_name='수량 포맷')),
                ('fmt_request', models.CharField(max_length=10, null=True, verbose_name='요청사항 포맷')),
            ],
            options={
                'db_table': 'order_formats',
                'managed': True,
                'verbose_name': 'Order Format',
                'verbose_name_plural': 'Order Formats',
            },
        ),
        migrations.AddField(
            model_name='tcretailer',
            name='order_format',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OrderFormats'),
        ),
    ]
