# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181003_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcretailer',
            name='pickteam',
        ),
    ]
