# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180701_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcretailer',
            old_name='pickteam',
            new_name='pickteam_many',
        ),
    ]
