# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181003_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcretailer',
            old_name='pickteam_test',
            new_name='pickteam',
        ),
    ]
