# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180701_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcretailer',
            name='pickteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tc_retailer_pickteam', to='app.TCPickteam'),
        ),
    ]
