# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_tcretailer_pickteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcretailer',
            name='pickteam_many',
        ),
    ]
