# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181003_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGMV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('orders_cnt', models.IntegerField()),
                ('tnsct_vol', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='wsbytcgroup',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.TCOrg'),
        ),
    ]
