# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181004_0232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyGMV',
        ),
    ]
