# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_tcretailer_pickteam_many'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wsbyuser',
            options={'managed': True, 'verbose_name': "TCGroup's Wholesaler", 'verbose_name_plural': "TCGroup's Wholesalers"},
        ),
        migrations.AlterModelTable(
            name='wsbyuser',
            table='wsbytcgroup',
        ),
    ]
