# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_dailygmv'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGMV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('orders_cnt', models.IntegerField()),
                ('tnsct_vol', models.BigIntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'dailygmv',
            },
        ),
    ]
