# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180702_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WsByUser',
            new_name='WsByTCGroup',
        ),
    ]
