# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_dailygmv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wholesalers',
            fields=[
                ('ws_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ws_name', models.CharField(max_length=512)),
                ('building_name', models.CharField(max_length=512)),
                ('location', models.CharField(max_length=20)),
                ('product_count', models.IntegerField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('floor', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'wholesalers',
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
