# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180702_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsbytcgroup',
            name='group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.TCGroup'),
        ),
    ]
