# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_wsbytcgroup_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsbytcgroup',
            name='user',
        ),
    ]
