# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20181010_1628'),
    ]

    operations = [
    ]
