# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_wsbytcgroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsbytcgroup',
            name='col',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
