# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20181010_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcretailer',
            name='org',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TCOrg'),
        ),
    ]
