# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_wsbytcgroup_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsbytcgroup',
            name='col',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
