# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180703_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcuser',
            name='full_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
