# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20181010_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsbytcgroup',
            name='group',
        ),
        migrations.AddField(
            model_name='order',
            name='org',
            field=models.ForeignKey(db_column='pickteam_org', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TCOrg'),
        ),
        migrations.AlterField(
            model_name='tcorg',
            name='main_user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
