# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20181010_1637'),
    ]

    operations = [
    ]
