# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20181010_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcretailer',
            name='tcgroup_ptr',
        ),
        migrations.AddField(
            model_name='tcretailer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tcorg',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tcorg',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tcorg',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tcorg',
            name='bank_holder_name',
            field=models.CharField(blank=True, default='', max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tcorg',
            name='main_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
