# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_kakaotemplates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kakaotemplates',
            options={'verbose_name': 'Kakao Template', 'verbose_name_plural': 'Kakao Templates'},
        ),
        migrations.AddField(
            model_name='kakaotemplates',
            name='tmplName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
