# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-05 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180705_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcretailer',
            name='city',
            field=models.CharField(default='서울', max_length=10),
        ),
    ]
