# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_tcretailer_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
    ]
