# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20181015_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakaotemplates',
            name='cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
