# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20181015_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notify_order_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notify_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
