# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20180706_1828'),
    ]

    operations = [

    ]
