# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180706_1829'),
    ]

    operations = [
    ]
