# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20180709_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcgroup',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
