# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_tcgroup_type'),
    ]

    operations = [


    ]
