# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20180710_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Retailer'),
        ),
    ]
