# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20180710_2118'),
    ]

    operations = [
    ]
