# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20180710_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickteam_id',
        ),
        migrations.AddField(
            model_name='order',
            name='pickteam',
            field=models.ForeignKey(db_column='pickteam_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TCPickteam'),
        ),
        migrations.AlterField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TCRetailer'),
        ),
    ]
