# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20180710_2130'),
    ]

    operations = [
    ]
