# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_order_ws_store_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
