# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_order_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsbytcgroup',
            name='ws_phone_second',
            field=models.CharField(default='', max_length=30),
        ),
    ]
