# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_wsbytcgroup_ws_phone_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAddWsFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Bulk Ws Formats',
                'db_table': 'bulk_ws_formats',
                'verbose_name': 'Bulk Ws Format',
                'managed': True,
            },
        ),
    ]
