# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-20 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20180731_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderformats',
            name='fmt_datetime',
            field=models.CharField(max_length=20, null=True, verbose_name='날짜'),
        ),
    ]
