# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-11 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20180820_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parser',
            field=models.CharField(default='BaseParser', max_length=30),
        ),
    ]
