# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20180911_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
